"""empty message

Revision ID: e17a93cb4b53
Revises: 
Create Date: 2024-01-15 23:45:40.043532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a93cb4b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bit_package',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('testId', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('host', sa.Integer(), nullable=False),
    sa.Column('isRecived', sa.Boolean(), nullable=True),
    sa.Column('isSended', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'testId')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('makerId', sa.Integer(), nullable=False),
    sa.Column('ipv4', sa.String(length=255), nullable=False),
    sa.Column('departament', sa.String(length=255), nullable=False),
    sa.Column('domainName', sa.String(length=255), nullable=False),
    sa.Column('personName', sa.String(length=255), nullable=False),
    sa.Column('isOperative', sa.Boolean(), nullable=True),
    sa.Column('osId', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('makerId')
    )
    op.create_table('ping_test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('ping_test')
    op.drop_table('devices')
    op.drop_table('bit_package')
    # ### end Alembic commands ###
